// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkZBbcrnMFLa7j6vHMjUyGcXOnLwyxbZ0',
    appId: '1:255471066859:web:b2ae3798669aaaa556e8ae',
    messagingSenderId: '255471066859',
    projectId: 'arjun-test-app',
    authDomain: 'arjun-test-app.firebaseapp.com',
    storageBucket: 'arjun-test-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeDQpKBBzBXCmqeI73Py5A-vdaA3S-GSA',
    appId: '1:255471066859:android:aff6d6ee86daa20556e8ae',
    messagingSenderId: '255471066859',
    projectId: 'arjun-test-app',
    storageBucket: 'arjun-test-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ZFyc8lDD37zSe1ohw_8dkIV8hozqUwA',
    appId: '1:255471066859:ios:fbb237286a8e160156e8ae',
    messagingSenderId: '255471066859',
    projectId: 'arjun-test-app',
    storageBucket: 'arjun-test-app.appspot.com',
    iosBundleId: 'com.example.fireFlutterAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ZFyc8lDD37zSe1ohw_8dkIV8hozqUwA',
    appId: '1:255471066859:ios:25542e97d42176c756e8ae',
    messagingSenderId: '255471066859',
    projectId: 'arjun-test-app',
    storageBucket: 'arjun-test-app.appspot.com',
    iosBundleId: 'com.example.fireFlutterAppTest.RunnerTests',
  );
}
